version: 1.7.0.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build:
- cmd: build.cmd
