version: 1.3.0.{build}
branches:
  only:
  - develop
  - master
nuget:
  account_feed: true
image: Visual Studio 2015
configuration: Release
before_build:
- ps: .\patch-project-json.ps1
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
test_script:
- ps: '& .\run-test-with-coverage.ps1'
after_test:
artifacts:
- path: Artifacts\**\*.zip
notifications:
- provider: Slack
  auth_token:
    secure: hVY5v+riPN7MOCCvS3Jw1VpNogniBYpQ7RJAWrNwww07rnVTDGJyNQBfVZf6jpjM
  channel: developers-dsp
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false