version: 1.2.7.{build}
branches:
  only:
  - develop
  - master
nuget:
  account_feed: true
image: Visual Studio 2015
configuration: Release
before_build:
- ps: .\patch-project-json.ps1
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
test_script:
- ps: '& .\run-test-with-coverage.ps1'
after_test:
artifacts:
- path: Artifacts\**\*.zip
